repository: RainbowM12/RainbowM12.github.io
repository_url: https://github.com/RainbowM12/RainbowM12.github.io

timezone: Asia/Shanghai
lang: zh_CN

title: lysitheai · lysitheai-Navi
alias_en: lysitheai-Navi
alias_cn: lysitheai导航
description: A Navigation Website for BYR
keywords: lysitheai, lysitheai-Navi, lysitheai, BUPT, Navi, Navigation
url: https://rainbowm12.github.io/
established_at: "2016-10-01T00:00+08:00"

author: Rainbowm
author_url: https://irockbunny.com
organization: Rainbowm
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
